# Generated by Django 4.1.5 on 2023-01-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='ссылка')),
                ('avatar_url', models.CharField(default='отсутсвует', max_length=50, verbose_name='ссылка на аватарку')),
                ('name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('full_name', models.CharField(max_length=50, verbose_name='полное имя пользователя')),
                ('bio', models.TextField(default='отсутсвует', max_length=300, verbose_name='bio')),
                ('tags', models.TextField(default='отсутсвует', max_length=3000, verbose_name='подписки')),
                ('phone', models.CharField(default='отсутсвует', max_length=50, verbose_name='номер телефона, если есть')),
                ('link', models.CharField(default='отсутсвует', max_length=50, verbose_name='ссылка на сайт,если есть')),
                ('posts', models.IntegerField(default='отсутсвует', verbose_name='количество постов')),
                ('count_followers', models.IntegerField(default='отсутсвует', verbose_name='количество подписчиков')),
                ('followers', models.TextField(default='отсутсвует', max_length=3000, verbose_name='подписчики')),
                ('count_following', models.IntegerField(default='отсутсвует', verbose_name='количество подписок')),
                ('folowing', models.TextField(default='отсутсвует', max_length=3000, verbose_name='подписки')),
                ('user_id', models.CharField(max_length=50, verbose_name='id')),
            ],
            options={
                'verbose_name': 'Информация пользователя',
                'verbose_name_plural': 'Информация пользователей',
            },
        ),
    ]
